// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eszwejaambtfgyiklwds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzendlamFhbWJ0Zmd5aWtsd2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTU4NzEsImV4cCI6MjA2NTI5MTg3MX0.5BLWFUKq6_st1x8DhPzI0v-941RDkhx9MMQZT_cTgrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);